import type { ITeam, IFormatedTeamProject } from '@/types/teams.types';
import type { IMember } from '@/types/members.types';
import type { IFocusArea } from '@/types/shared.types';
import type { ITeamFocusAres } from '@/components/page/team-details/TeamFocusAreas/types';
import type { ITeamNewsItem } from '@/types/team-news.types';

// One full mock team. The detail-page sections only read the fields populated
// here. `logo` is left undefined so TeamDetails falls back to its dicebear
// default avatar (no remote-image domain config in this app).
export const MOCK_TEAM = {
  id: 'protocol-labs',
  name: 'Protocol Labs',
  shortDescription: 'Building protocols, tools, and services to radically improve the internet.',
  longDescription:
    '<p>Protocol Labs is an open-source R&amp;D lab that builds protocols, tools, and services to radically improve the internet. We drive breakthroughs in computing to push humanity forward — products include <strong>IPFS</strong>, <strong>Filecoin</strong>, and <strong>libp2p</strong>.</p><p>Our network spans hundreds of teams and thousands of builders working on decentralized storage, compute, networking, and cryptography.</p>',
  website: 'https://protocol.ai',
  twitter: 'https://twitter.com/protocollabs',
  linkedinHandle: 'https://www.linkedin.com/company/protocol-labs',
  telegramHandler: 'https://t.me/protocollabs',
  blog: 'https://protocol.ai/blog',
  contactMethod: 'https://protocol.ai/contact',
  fundingStage: { title: 'Growth' },
  isFund: true,
  industryTags: [
    { uid: 'i1', title: 'Infrastructure' },
    { uid: 'i2', title: 'Web3' },
    { uid: 'i3', title: 'Storage' },
    { uid: 'i4', title: 'Networking' },
    { uid: 'i5', title: 'Cryptography' },
    { uid: 'i6', title: 'Compute' },
  ],
  membershipSources: [
    { uid: 'm1', title: 'Protocol Labs' },
    { uid: 'm2', title: 'Filecoin Foundation' },
  ],
  communityAffiliations: [
    { uid: 'c1', title: 'IPFS Ecosystem' },
    { uid: 'c2', title: 'Filecoin Network' },
    { uid: 'c3', title: 'libp2p Working Group' },
  ],
  technologies: [
    { uid: 'te1', title: 'Go' },
    { uid: 'te2', title: 'Rust' },
  ],
  investorProfile: {
    uid: 'ip1',
    investmentFocus: ['Decentralized Storage', 'Web3 Infrastructure', 'Developer Tools'],
    typicalCheckSize: '500000',
    createdAt: '2023-01-01',
    updatedAt: '2023-06-01',
    teamUid: 'protocol-labs',
    memberUid: null,
    secRulesAccepted: true,
    investInStartupStages: ['Pre-Seed', 'Seed', 'Series A'],
    investInFundTypes: ['Venture', 'Ecosystem'],
  },
  teamFocusAreas: [],
  maintainingProjects: [],
  contributingProjects: [],
  asks: [],
} satisfies Partial<ITeam>;

export const MOCK_MEMBERS = [
  {
    id: 'mem-1',
    name: 'Juan Benet',
    teamLead: true,
    skills: [
      { uid: 's1', title: 'Distributed Systems' },
      { uid: 's2', title: 'Protocol Design' },
      { uid: 's3', title: 'Go' },
      { uid: 's4', title: 'Cryptography' },
    ],
    teams: [{ id: 'protocol-labs', name: 'Protocol Labs', role: 'Founder & CEO' }],
  },
  {
    id: 'mem-2',
    name: 'Molly Mackinlay',
    teamLead: false,
    skills: [
      { uid: 's5', title: 'Product' },
      { uid: 's6', title: 'Engineering Leadership' },
    ],
    teams: [{ id: 'protocol-labs', name: 'Protocol Labs', role: 'Project Lead, IPFS' }],
  },
  {
    id: 'mem-3',
    name: 'David Dias',
    teamLead: false,
    skills: [
      { uid: 's7', title: 'libp2p' },
      { uid: 's8', title: 'Networking' },
      { uid: 's9', title: 'JavaScript' },
    ],
    teams: [{ id: 'protocol-labs', name: 'Protocol Labs', role: 'Research Engineer' }],
  },
  {
    id: 'mem-4',
    name: 'Steven Allen',
    teamLead: false,
    skills: [
      { uid: 's10', title: 'Rust' },
      { uid: 's11', title: 'Systems Programming' },
    ],
    teams: [{ id: 'protocol-labs', name: 'Protocol Labs', role: 'Engineering' }],
  },
] as unknown as IMember[];

// Focus areas: top-level groups, each with children that match teamFocusAreas
// by uid (the hook joins them).
export const MOCK_FOCUS_AREAS: IFocusArea[] = [
  {
    uid: 'fa-infra',
    title: 'Internet Infrastructure',
    children: [
      { uid: 'fa-storage', title: 'Decentralized Storage' },
      { uid: 'fa-networking', title: 'Peer-to-Peer Networking' },
      { uid: 'fa-compute', title: 'Distributed Compute' },
    ],
  } as IFocusArea,
  {
    uid: 'fa-research',
    title: 'Research',
    children: [
      { uid: 'fa-crypto', title: 'Applied Cryptography' },
      { uid: 'fa-consensus', title: 'Consensus Protocols' },
    ],
  } as IFocusArea,
];

export const MOCK_TEAM_FOCUS_AREAS: ITeamFocusAres[] = [
  { uid: 'fa-storage', title: 'Decentralized Storage' },
  { uid: 'fa-networking', title: 'Peer-to-Peer Networking' },
  { uid: 'fa-compute', title: 'Distributed Compute' },
  { uid: 'fa-crypto', title: 'Applied Cryptography' },
];

export const MOCK_PROJECTS = [
  {
    uid: 'proj-ipfs',
    name: 'IPFS',
    tagline: 'A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.',
    lookingForFunding: false,
    isMaintainingProject: true,
    isDeleted: false,
    hasEditAccess: false,
  },
  {
    uid: 'proj-filecoin',
    name: 'Filecoin',
    tagline: 'A decentralized storage network designed to store humanity’s most important information.',
    lookingForFunding: true,
    isMaintainingProject: true,
    isDeleted: false,
    hasEditAccess: false,
  },
  {
    uid: 'proj-libp2p',
    name: 'libp2p',
    tagline: 'A modular network stack for peer-to-peer applications.',
    lookingForFunding: false,
    isMaintainingProject: false,
    isDeleted: false,
    hasEditAccess: false,
  },
  {
    uid: 'proj-drand',
    name: 'drand',
    tagline: 'A distributed randomness beacon producing publicly verifiable random values.',
    lookingForFunding: false,
    isMaintainingProject: false,
    isDeleted: false,
    hasEditAccess: false,
  },
] as unknown as IFormatedTeamProject[];

/* ---------------- Team news (mirrors ITeamNewsItem from the homepage) ---------------- */
export const MOCK_NEWS: ITeamNewsItem[] = [
  {
    uid: 'news-1',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'ANNOUNCEMENT',
    eventDate: '2026-06-21T10:00:00.000Z',
    title: 'Protocol Labs announced the next IPFS mainnet upgrade, introducing faster content routing and lower retrieval latency.',
    summary: null,
    sourceUrl: 'https://x.com/protocollabs',
    sourceDomain: 'x.com',
    tags: ['IPFS'],
    focusAreas: ['Infrastructure'],
    subFocusAreas: [],
    createdAt: '2026-06-21T10:00:00.000Z',
    discussion: { count: 0, latestTopicUrl: null },
  },
  {
    uid: 'news-2',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'LAUNCH',
    eventDate: '2026-06-21T09:00:00.000Z',
    title: 'Filecoin Foundation launched a new grants round focused on verifiable storage for AI training datasets.',
    summary: null,
    sourceUrl: 'https://x.com/filecoin',
    sourceDomain: 'x.com',
    tags: ['Filecoin', 'Grants'],
    focusAreas: ['Storage'],
    subFocusAreas: [],
    createdAt: '2026-06-21T09:00:00.000Z',
    discussion: { count: 3, latestTopicUrl: null },
  },
  {
    uid: 'news-3',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'PARTNERSHIP',
    eventDate: '2026-06-20T14:00:00.000Z',
    title: 'libp2p partnered with a major L2 to standardize peer discovery across rollup networks.',
    summary: null,
    sourceUrl: 'https://x.com/libp2p',
    sourceDomain: 'x.com',
    tags: ['libp2p'],
    focusAreas: ['Networking'],
    subFocusAreas: [],
    createdAt: '2026-06-20T14:00:00.000Z',
    discussion: { count: 1, latestTopicUrl: null },
  },
  {
    uid: 'news-4',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'MILESTONE',
    eventDate: '2026-06-18T12:00:00.000Z',
    title: 'The Filecoin network crossed 2,000 PiB of active storage deals, a new all-time high for the protocol.',
    summary: null,
    sourceUrl: 'https://x.com/filecoin',
    sourceDomain: 'x.com',
    tags: ['Filecoin'],
    focusAreas: ['Storage'],
    subFocusAreas: [],
    createdAt: '2026-06-18T12:00:00.000Z',
    discussion: { count: 0, latestTopicUrl: null },
  },
  {
    uid: 'news-5',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'FUNDING',
    eventDate: '2026-06-16T08:00:00.000Z',
    title: 'A Protocol Labs–incubated team closed a seed round to build decentralized compute markets on top of IPFS.',
    summary: null,
    sourceUrl: 'https://x.com/protocollabs',
    sourceDomain: 'x.com',
    tags: ['Funding'],
    focusAreas: ['Infrastructure'],
    subFocusAreas: [],
    createdAt: '2026-06-16T08:00:00.000Z',
    discussion: { count: 2, latestTopicUrl: null },
  },
  {
    uid: 'news-6',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'ANNOUNCEMENT',
    eventDate: '2026-06-14T11:00:00.000Z',
    title: 'IPFS Camp 2026 dates announced, with a track dedicated to content-addressed AI pipelines.',
    summary: null,
    sourceUrl: 'https://x.com/protocollabs',
    sourceDomain: 'x.com',
    tags: ['Events'],
    focusAreas: ['Infrastructure'],
    subFocusAreas: [],
    createdAt: '2026-06-14T11:00:00.000Z',
    discussion: { count: 0, latestTopicUrl: null },
  },
  {
    uid: 'news-7',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'LAUNCH',
    eventDate: '2026-06-11T15:00:00.000Z',
    title: 'A new retrieval market client shipped, cutting cold-storage retrieval times on Filecoin by ~40%.',
    summary: null,
    sourceUrl: 'https://x.com/filecoin',
    sourceDomain: 'x.com',
    tags: ['Filecoin'],
    focusAreas: ['Storage'],
    subFocusAreas: [],
    createdAt: '2026-06-11T15:00:00.000Z',
    discussion: { count: 4, latestTopicUrl: null },
  },
  {
    uid: 'news-8',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'PARTNERSHIP',
    eventDate: '2026-06-08T09:00:00.000Z',
    title: 'Protocol Labs joined a cross-industry working group on decentralized identity standards.',
    summary: null,
    sourceUrl: 'https://x.com/protocollabs',
    sourceDomain: 'x.com',
    tags: ['Identity'],
    focusAreas: ['Networking'],
    subFocusAreas: [],
    createdAt: '2026-06-08T09:00:00.000Z',
    discussion: { count: 1, latestTopicUrl: null },
  },
  {
    uid: 'news-9',
    teamUid: 'protocol-labs',
    teamName: 'Protocol Labs',
    teamLogoUrl: null,
    eventType: 'OTHER',
    eventDate: '2026-06-04T13:00:00.000Z',
    title: 'Quarterly ecosystem report published, highlighting growth across storage, compute, and networking projects.',
    summary: null,
    sourceUrl: 'https://x.com/protocollabs',
    sourceDomain: 'x.com',
    tags: ['Report'],
    focusAreas: ['Infrastructure'],
    subFocusAreas: [],
    createdAt: '2026-06-04T13:00:00.000Z',
    discussion: { count: 0, latestTopicUrl: null },
  },
];
