export interface Member {
    id: number
    name: string
    image: string
  }
  
  export interface Team {
    id: number
    name: string
    volume: number
    hosts: string[]
    speakers: string[]
  }
  
  // Expanded mock data for members
  export const mockMembers: Member[] = [
    { id: 1, name: "Alex Johnson", image: "/icons/default-user-profile.svg" },
    { id: 2, name: "Maria Garcia", image: "/icons/default-user-profile.svg" },
    { id: 3, name: "David Kim", image: "/icons/default-user-profile.svg" },
    { id: 4, name: "Sarah Patel", image: "/icons/default-user-profile.svg" },
    { id: 5, name: "James Wilson", image: "/icons/default-user-profile.svg" },
    { id: 6, name: "Emma Rodriguez", image: "/icons/default-user-profile.svg" },
    { id: 7, name: "Michael Chen", image: "/icons/default-user-profile.svg" },
    { id: 8, name: "Olivia Martinez", image: "/icons/default-user-profile.svg" },
    { id: 9, name: "William Taylor", image: "/icons/default-user-profile.svg" },
    { id: 10, name: "Sophia Lee", image: "/icons/default-user-profile.svg" },
    { id: 11, name: "Daniel Brown", image: "/icons/default-user-profile.svg" },
    { id: 12, name: "Isabella Clark", image: "/icons/default-user-profile.svg" },
    { id: 13, name: "Ethan Wright", image: "/icons/default-user-profile.svg" },
    { id: 14, name: "Ava Lopez", image: "/icons/default-user-profile.svg" },
    { id: 15, name: "Noah Gonzalez", image: "/icons/default-user-profile.svg" },
    { id: 16, name: "Mia Hernandez", image: "/icons/default-user-profile.svg" },
    { id: 17, name: "Lucas Perez", image: "/icons/default-user-profile.svg" },
    { id: 18, name: "Charlotte Scott", image: "/icons/default-user-profile.svg" },
    { id: 19, name: "Benjamin Green", image: "/icons/default-user-profile.svg" },
    { id: 20, name: "Amelia Adams", image: "/icons/default-user-profile.svg" },
    { id: 21, name: "Raj Patel", image: "/icons/default-user-profile.svg" },
    { id: 22, name: "Zoe Thompson", image: "/icons/default-user-profile.svg" },
    { id: 23, name: "Hiroshi Tanaka", image: "/icons/default-user-profile.svg" },
    { id: 24, name: "Elena Petrova", image: "/icons/default-user-profile.svg" },
    { id: 25, name: "Omar Hassan", image: "/icons/default-user-profile.svg" },
    { id: 26, name: "Fatima Ahmed", image: "/icons/default-user-profile.svg" },
    { id: 27, name: "Carlos Mendoza", image: "/icons/default-user-profile.svg" },
    { id: 28, name: "Priya Sharma", image: "/icons/default-user-profile.svg" },
    { id: 29, name: "Jamal Wilson", image: "/icons/default-user-profile.svg" },
    { id: 30, name: "Aisha Johnson", image: "/icons/default-user-profile.svg" },
    { id: 31, name: "Wei Zhang", image: "/icons/default-user-profile.svg" },
    { id: 32, name: "Sven Johansson", image: "/icons/default-user-profile.svg" },
    { id: 33, name: "Layla Mahmoud", image: "/icons/default-user-profile.svg" },
    { id: 34, name: "Diego Fernandez", image: "/icons/default-user-profile.svg" },
    { id: 35, name: "Nadia Ivanova", image: "/icons/default-user-profile.svg" },
    { id: 36, name: "Kwame Osei", image: "/icons/default-user-profile.svg" },
    { id: 37, name: "Yuki Nakamura", image: "/icons/default-user-profile.svg" },
    { id: 38, name: "Gabriela Santos", image: "/icons/default-user-profile.svg" },
    { id: 39, name: "Ibrahim Al-Farsi", image: "/icons/default-user-profile.svg" },
    { id: 40, name: "Leila Nguyen", image: "/icons/default-user-profile.svg" },
    { id: 41, name: "Mateo Rossi", image: "/icons/default-user-profile.svg" },
    { id: 42, name: "Anika Patel", image: "/icons/default-user-profile.svg" },
    { id: 43, name: "Javier Morales", image: "/icons/default-user-profile.svg" },
    { id: 44, name: "Mei Lin", image: "/icons/default-user-profile.svg" },
    { id: 45, name: "Kofi Mensah", image: "/icons/default-user-profile.svg" },
    { id: 46, name: "Valentina Ricci", image: "/icons/default-user-profile.svg" },
    { id: 47, name: "Tariq Khan", image: "/icons/default-user-profile.svg" },
    { id: 48, name: "Ingrid Larsen", image: "/icons/default-user-profile.svg" },
    { id: 49, name: "Rafael Costa", image: "/icons/default-user-profile.svg" },
    { id: 50, name: "Amara Okafor", image: "/icons/default-user-profile.svg" },
  ]
  
  // Mock data for teams with collaboration volume - matching the Figma design
  export const mockTeams: Team[] = [
    {
      id: 1,
      name: "Akave",
      volume: 100,
      hosts: ["Alex Johnson", "Maria Garcia"],
      speakers: ["David Kim", "Sarah Patel", "James Wilson"],
    },
    {
      id: 2,
      name: "Protocol Labs",
      volume: 95,
      hosts: ["Emma Rodriguez", "Michael Chen"],
      speakers: ["Olivia Martinez", "William Taylor", "Sophia Lee"],
    },
    {
      id: 3,
      name: "Titan Network",
      volume: 40,
      hosts: ["Daniel Brown"],
      speakers: ["Isabella Clark", "Ethan Wright"],
    },
    {
      id: 4,
      name: "Gitcoin",
      volume: 35,
      hosts: ["Ava Lopez"],
      speakers: ["Noah Gonzalez", "Mia Hernandez"],
    },
    {
      id: 5,
      name: "ABT",
      volume: 30,
      hosts: ["Lucas Perez"],
      speakers: ["Charlotte Scott"],
    },
    {
      id: 6,
      name: "Kariba Labs",
      volume: 28,
      hosts: ["Benjamin Green"],
      speakers: ["Amelia Adams"],
    },
    {
      id: 7,
      name: "Spruce ID",
      volume: 25,
      hosts: ["Raj Patel"],
      speakers: ["Zoe Thompson"],
    },
    {
      id: 8,
      name: "libp2b",
      volume: 20,
      hosts: ["Hiroshi Tanaka"],
      speakers: ["Elena Petrova"],
    },
    {
      id: 9,
      name: "NFT.Storage",
      volume: 18,
      hosts: ["Omar Hassan"],
      speakers: ["Fatima Ahmed"],
    },
    {
      id: 10,
      name: "Lit Protocol",
      volume: 15,
      hosts: ["Carlos Mendoza"],
      speakers: ["Priya Sharma"],
    },
    {
      id: 11,
      name: "Celestia",
      volume: 14,
      hosts: ["Jamal Wilson"],
      speakers: ["Aisha Johnson"],
    },
    {
      id: 12,
      name: "Crytio",
      volume: 12,
      hosts: ["Wei Zhang"],
      speakers: ["Sven Johansson"],
    },
    {
      id: 13,
      name: "Orange Protocol",
      volume: 10,
      hosts: ["Layla Mahmoud"],
      speakers: ["Diego Fernandez"],
    },
    {
      id: 14,
      name: "Funding Rate",
      volume: 9,
      hosts: ["Nadia Ivanova"],
      speakers: ["Kwame Osei"],
    },
    {
      id: 15,
      name: "Filecoinfoundation",
      volume: 8,
      hosts: ["Yuki Nakamura"],
      speakers: ["Gabriela Santos"],
    },
    {
      id: 16,
      name: "Molecule",
      volume: 7,
      hosts: ["Ibrahim Al-Farsi"],
      speakers: ["Leila Nguyen"],
    },
    {
      id: 17,
      name: "Randamu",
      volume: 6,
      hosts: ["Mateo Rossi"],
      speakers: ["Anika Patel"],
    },
    {
      id: 18,
      name: "Gensyn",
      volume: 5,
      hosts: ["Javier Morales"],
      speakers: ["Mei Lin"],
    },
    {
      id: 19,
      name: "Web3mine",
      volume: 4,
      hosts: ["Kofi Mensah"],
      speakers: ["Valentina Ricci"],
    },
    {
      id: 20,
      name: "Ethereum",
      volume: 55,
      hosts: ["Tariq Khan", "Ingrid Larsen"],
      speakers: ["Rafael Costa", "Amara Okafor"],
    },
    {
      id: 21,
      name: "Polkadot",
      volume: 75,
      hosts: ["Alex Johnson", "Maria Garcia"],
      speakers: ["David Kim", "Sarah Patel", "James Wilson"],
    },
    {
      id: 22,
      name: "Solana",
      volume: 70,
      hosts: ["Emma Rodriguez", "Michael Chen"],
      speakers: ["Olivia Martinez", "William Taylor"],
    },
    {
      id: 23,
      name: "Chainlink",
      volume: 65,
      hosts: ["Daniel Brown", "Isabella Clark"],
      speakers: ["Ethan Wright", "Ava Lopez"],
    },
    {
      id: 24,
      name: "Uniswap",
      volume: 60,
      hosts: ["Noah Gonzalez"],
      speakers: ["Mia Hernandez", "Lucas Perez", "Charlotte Scott"],
    },
    {
      id: 25,
      name: "Aave",
      volume: 55,
      hosts: ["Benjamin Green", "Amelia Adams"],
      speakers: ["Raj Patel", "Zoe Thompson"],
    },
    {
      id: 26,
      name: "Compound",
      volume: 50,
      hosts: ["Hiroshi Tanaka"],
      speakers: ["Elena Petrova", "Omar Hassan", "Fatima Ahmed"],
    },
  ]
  