import { IDeal } from '@/types/deals.types';

export const MOCK_DEALS: IDeal[] = [
  {
    id: 'deal-1',
    title: 'Vercel',
    description: 'Free Vercel Pro plan for early-stage startups building on modern web frameworks.',
    aboutHtml: `<p>Perfect for teams building production applications that need fast global delivery and zero-config CI/CD from GitHub, GitLab, or Bitbucket.</p><h3>PL funded teams</h3><p>You get Vercel's Pro plan for 12 months which includes unlimited deployments, 1TB bandwidth, Edge Functions, Web Analytics, and priority support.</p><h3>Founders Forge teams</h3><p>You get Vercel's Pro plan for 3 months which includes unlimited deployments, 1TB bandwidth, Edge Functions, Web Analytics, and priority support.</p>`,
    redemptionHtml: `<h3>Steps to redeem</h3><ol><li>Click the <a href="https://vercel.com/startups">signup link</a> below to access the special PL network offer page.</li><li>Sign in with your account.</li><li>Select Pro during onboarding — your 12 months free will be applied automatically.</li><li>Verify your PL network affiliation via the form on the next page.</li><li>Your Pro account will be activated within 1 business day.</li></ol>`,
    logoUrl: '/images/deals/vercel.svg',
    externalUrl: 'https://vercel.com/startups',
    categories: ['hosting-infrastructure'],
    audience: ['all-founders'],
    usersCount: 51,
    issuesCount: 0,
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'deal-2',
    title: 'GitHub',
    description: '50% off GitHub Enterprise for the first year for PL network teams.',
    aboutHtml: `<p>GitHub Enterprise gives your team advanced security, compliance, and flexible deployment options. Ideal for organizations with strict data residency or IP protection requirements.</p><h3>PL funded teams</h3><p>50% off GitHub Enterprise Cloud for 12 months, including advanced audit log, SAML SSO, and GitHub Advanced Security.</p><h3>Founders Forge teams</h3><p>50% off GitHub Enterprise Cloud for 6 months with the same feature set.</p>`,
    redemptionHtml: `<h3>Steps to redeem</h3><ol><li>Click the <a href="https://github.com/enterprise">signup link</a> below to access the special PL network offer page.</li><li>Sign in with your GitHub account.</li><li>Select Enterprise Cloud during setup — your 50% discount will be applied automatically.</li><li>Verify your PL network affiliation via the form on the next page.</li><li>Your Enterprise account will be activated within 1 business day.</li></ol>`,
    logoUrl: '/images/deals/github.svg',
    externalUrl: 'https://github.com/enterprise',
    categories: ['developer-tools'],
    audience: ['all-founders'],
    usersCount: 78,
    issuesCount: 1,
    createdAt: '2026-02-28T00:00:00Z',
  },
  {
    id: 'deal-3',
    title: 'Linear',
    description: 'Free Linear Business plan for 1 year for fast-moving engineering teams.',
    aboutHtml: `<p>Linear helps engineering teams streamline issue tracking, project management, and product roadmaps with a fast, keyboard-first interface.</p><h3>PL funded teams</h3><p>Free Linear Business plan for 12 months for up to 50 members, including cycles, projects, triage, and Slack/GitHub integrations.</p>`,
    redemptionHtml: `<h3>Steps to redeem</h3><ol><li>Click the <a href="https://linear.app/startups">signup link</a> below to access the special PL network offer page.</li><li>Sign in with your Linear account.</li><li>Select Business plan during onboarding — your 12 months free will be applied automatically.</li><li>Verify your PL network affiliation via the form on the next page.</li><li>Your Business account will be activated within 1 business day.</li></ol>`,
    logoUrl: '/images/deals/linear.svg',
    externalUrl: 'https://linear.app/startups',
    categories: ['developer-tools'],
    audience: ['pl-funded-founders'],
    usersCount: 40,
    issuesCount: 0,
    createdAt: '2026-02-25T00:00:00Z',
  },
  {
    id: 'deal-4',
    title: 'Figma',
    description: 'Free Figma Organization plan for qualifying PL-funded startups.',
    aboutHtml: `<p>Figma is the leading collaborative design tool for teams building digital products. Design, prototype, and hand off — all in one place.</p><h3>What you get</h3><p>Free Figma Organization plan for 12 months, including unlimited projects, team libraries, branching, and Dev Mode for seamless design-to-code handoff.</p>`,
    logoUrl: '/images/deals/figma.svg',
    externalUrl: 'https://figma.com/startups',
    categories: ['design-collaboration'],
    audience: ['all-founders'],
    usersCount: 90,
    issuesCount: 0,
    createdAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'deal-5',
    title: 'Notion',
    description: "6 months free on Notion's Team plan for up to 20 members.",
    aboutHtml: `<p>Notion combines notes, docs, wikis, and project management into one workspace. Perfect for fast-growing teams that want a single source of truth.</p><h3>PL funded teams</h3><p>6 months free on Notion's Team plan for up to 20 members, including unlimited blocks, advanced permissions, and admin tools.</p><h3>Founders Forge teams</h3><p>3 months free on Notion's Team plan for up to 10 members.</p>`,
    logoUrl: '/images/deals/notion.svg',
    externalUrl: 'https://notion.so/startups',
    categories: ['design-collaboration'],
    audience: ['all-founders'],
    usersCount: 65,
    issuesCount: 0,
    createdAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'deal-6',
    title: 'Supabase',
    description: 'Use credits for database and authentication services in your app.',
    logoUrl: '/images/deals/supabase.svg',
    externalUrl: 'https://supabase.com/startups',
    categories: ['developer-tools'],
    audience: ['all-founders'],
    usersCount: 30,
    issuesCount: 0,
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'deal-7',
    title: 'Datadog',
    description: "Monitor your applications with Datadog's advanced features.",
    logoUrl: '/images/deals/datadog.svg',
    externalUrl: 'https://datadog.com/startups',
    categories: ['analytics-monitoring'],
    audience: ['all-founders'],
    usersCount: 25,
    issuesCount: 0,
    createdAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'deal-8',
    title: 'Sentry',
    description: "Credits to use Sentry's error tracking services for your applications.",
    logoUrl: '/images/deals/sentry.svg',
    externalUrl: 'https://sentry.io/startups',
    categories: ['analytics-monitoring'],
    audience: ['all-founders'],
    usersCount: 70,
    issuesCount: 0,
    createdAt: '2026-01-30T00:00:00Z',
  },
  {
    id: 'deal-9',
    title: 'PostHog',
    description: 'Get started with PostHog for product analytics without costs.',
    logoUrl: '/images/deals/posthog.svg',
    externalUrl: 'https://posthog.com/startups',
    categories: ['analytics-monitoring'],
    audience: ['all-founders'],
    usersCount: 85,
    issuesCount: 0,
    createdAt: '2026-01-25T00:00:00Z',
  },
  {
    id: 'deal-10',
    title: 'Cloudflare',
    description: "Utilize Cloudflare's CDN and security features for your startup.",
    logoUrl: '/images/deals/cloudflare.svg',
    externalUrl: 'https://cloudflare.com/startups',
    categories: ['security-compliance'],
    audience: ['pl-funded-founders'],
    usersCount: 45,
    issuesCount: 0,
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'deal-11',
    title: 'AWS',
    description: 'Up to $100K in AWS credits for qualifying PL network startups.',
    logoUrl: '/images/deals/aws.svg',
    externalUrl: 'https://aws.amazon.com/startups',
    categories: ['hosting-infrastructure'],
    audience: ['pl-funded-founders'],
    usersCount: 120,
    issuesCount: 0,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'deal-12',
    title: 'Stripe',
    description: 'Waived Stripe fees for the first $1M in processing for PL founders.',
    logoUrl: '/images/deals/stripe.svg',
    externalUrl: 'https://stripe.com/startups',
    categories: ['developer-tools'],
    audience: ['all-founders'],
    usersCount: 95,
    issuesCount: 0,
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'deal-13',
    title: 'Snyk',
    description: 'Free Snyk Team plan for open-source security scanning.',
    logoUrl: '/images/deals/snyk.svg',
    externalUrl: 'https://snyk.io/startups',
    categories: ['security-compliance'],
    audience: ['all-founders'],
    usersCount: 35,
    issuesCount: 0,
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'deal-14',
    title: '1Password',
    description: 'Free 1Password Teams for 1 year for PL-funded startups.',
    logoUrl: '/images/deals/1password.svg',
    externalUrl: 'https://1password.com/startups',
    categories: ['security-compliance'],
    audience: ['pl-funded-founders'],
    usersCount: 55,
    issuesCount: 0,
    createdAt: '2025-12-28T00:00:00Z',
  },
  {
    id: 'deal-15',
    title: 'Mixpanel',
    description: 'Free Mixpanel Growth plan for 1 year with full analytics suite.',
    logoUrl: '/images/deals/mixpanel.svg',
    externalUrl: 'https://mixpanel.com/startups',
    categories: ['analytics-monitoring'],
    audience: ['all-founders'],
    usersCount: 42,
    issuesCount: 1,
    createdAt: '2025-12-20T00:00:00Z',
  },
  {
    id: 'deal-16',
    title: 'Miro',
    description: 'Free Miro Business plan for collaborative whiteboarding.',
    logoUrl: '/images/deals/miro.svg',
    externalUrl: 'https://miro.com/startups',
    categories: ['design-collaboration'],
    audience: ['all-founders'],
    usersCount: 38,
    issuesCount: 0,
    createdAt: '2025-12-15T00:00:00Z',
  },
  {
    id: 'deal-17',
    title: 'Render',
    description: 'Free Render Pro hosting for 6 months for PL network teams.',
    logoUrl: '/images/deals/render.svg',
    externalUrl: 'https://render.com/startups',
    categories: ['hosting-infrastructure'],
    audience: ['all-founders'],
    usersCount: 22,
    issuesCount: 0,
    createdAt: '2025-12-10T00:00:00Z',
  },
  {
    id: 'deal-18',
    title: 'Vanta',
    description: 'SOC 2 compliance automation with discounted Vanta plan.',
    logoUrl: '/images/deals/vanta.svg',
    externalUrl: 'https://vanta.com/startups',
    categories: ['security-compliance'],
    audience: ['pl-funded-founders'],
    usersCount: 18,
    issuesCount: 0,
    createdAt: '2025-12-05T00:00:00Z',
  },
];
