import type { FounderDetail, FounderItem, KpiSummary } from '@/services/founders/types';

// ── Founders ──────────────────────────────────────────────────────────────────
// Stored as FounderDetail (a superset of FounderItem) so the drawer can read the
// full record without a second fetch. Updated for the new Founder DB design:
// criteria headline, pedigree, thesis/focus area, signal flags, last-signal date,
// and PLN Proximity. alignmentMax / plvsScore are kept for the v0 alignment view.

type Signal = 'raising' | 'cofounder' | 'stealth' | 'nearNetwork' | 'plAligned';

type Seed = {
  name: string;
  headline: string;
  pedigree?: string;
  focusArea: string;
  alignment: number;
  plvs?: number;
  plnProximity?: number;
  funds: ('PLVS' | 'NEURO' | 'CRYPTO')[];
  sources: string[];
  status: FounderItem['reviewState']['status'];
  feedback?: FounderItem['reviewState']['feedback'];
  signals?: Signal[];
  lastSignalAt: string;
  bio?: string;
  topics?: string[];
  github?: string;
  website?: string;
  linkedin?: string;
  twitter?: string;
};

const SEEDS: Seed[] = [
  {
    name: 'Dr. Mei Lin',
    headline: 'PLVS fit · agent-orchestration runtime · just shipped',
    pedigree: 'MIT CSAIL PhD · ex-core maintainer, vLLM',
    focusArea: 'AI agents',
    alignment: 0.96,
    plvs: 91,
    plnProximity: 0.82,
    funds: ['PLVS'],
    sources: ['GitHub', 'arXiv', 'Crunchbase'],
    status: 'approved',
    feedback: 'good',
    signals: ['nearNetwork', 'plAligned', 'stealth'],
    lastSignalAt: '2026-06-19',
    bio: 'PhD in distributed systems. Built a fault-tolerant scheduler for multi-agent LLM workloads.',
    topics: ['agents', 'llm-infra', 'scheduling'],
    github: 'meilin',
    website: 'https://meilin.dev',
    twitter: 'meilin_ai',
  },
  {
    name: 'Tomás Herrera',
    headline: 'PLVS fit · LLM eval platform · stealth-launching',
    pedigree: 'ex-Anthropic infra (4 yrs)',
    focusArea: 'LLM infra',
    alignment: 0.94,
    plvs: 88,
    plnProximity: 0.74,
    funds: ['PLVS'],
    sources: ['LinkedIn', 'GitHub'],
    status: 'in-review',
    signals: ['raising', 'stealth', 'nearNetwork'],
    lastSignalAt: '2026-06-21',
    bio: 'Spent four years on evaluation infrastructure. Building continuous-eval for agentic systems.',
    topics: ['evals', 'llm-infra', 'observability'],
    github: 'therrera',
    linkedin: 'https://linkedin.com/in/therrera',
  },
  {
    name: 'Aisha Bello',
    headline: 'Neuro fit · closed-loop BCI · demo went viral',
    pedigree: 'Stanford Neuro · Nature Neurosci. author',
    focusArea: 'Neurotech / BCI',
    alignment: 0.92,
    plvs: 72,
    plnProximity: 0.4,
    funds: ['NEURO', 'PLVS'],
    sources: ['X', 'arXiv', 'Press'],
    status: 'in-review',
    signals: ['raising'],
    lastSignalAt: '2026-06-20',
    bio: 'Neuroscientist building closed-loop brain–computer interfaces for assistive applications.',
    topics: ['bci', 'neurotech', 'signal-processing'],
    twitter: 'aishabello',
  },
  {
    name: 'Yuki Tanaka',
    headline: 'Crypto fit · ZK prover toolkit · 2.3k stars in 6 wks',
    pedigree: 'ex-protocol eng, a16z crypto portfolio co',
    focusArea: 'ZK / cryptography',
    alignment: 0.89,
    plvs: 79,
    plnProximity: 0.55,
    funds: ['CRYPTO'],
    sources: ['GitHub', 'Mirror'],
    status: 'new',
    signals: ['cofounder'],
    lastSignalAt: '2026-06-18',
    bio: 'Cryptographer building a high-performance ZK prover toolkit.',
    topics: ['zk', 'cryptography', 'proving-systems'],
    github: 'yukit',
  },
  {
    name: 'Priya Nair',
    headline: 'PLVS · verifiable compute for AI inference',
    pedigree: 'ex-Protocol Labs research',
    focusArea: 'Verifiable compute',
    alignment: 0.87,
    plvs: 83,
    plnProximity: 0.91,
    funds: ['PLVS', 'CRYPTO'],
    sources: ['GitHub', 'Forum', 'arXiv'],
    status: 'approved',
    feedback: 'good',
    signals: ['nearNetwork', 'plAligned'],
    lastSignalAt: '2026-06-15',
    bio: 'Researcher working on verifiable off-chain compute for AI inference workloads.',
    topics: ['verifiable-compute', 'ai-infra'],
    github: 'priyanair',
    website: 'https://priya.systems',
  },
  {
    name: 'Lucas Almeida',
    headline: 'PLVS · robotics foundation models',
    pedigree: 'hired 2 ex-DeepMind researchers',
    focusArea: 'Robotics',
    alignment: 0.85,
    plvs: 76,
    plnProximity: 0.33,
    funds: ['PLVS'],
    sources: ['LinkedIn', 'Press'],
    status: 'new',
    signals: ['raising', 'cofounder'],
    lastSignalAt: '2026-06-12',
    topics: ['robotics', 'foundation-models'],
    linkedin: 'https://linkedin.com/in/lalmeida',
  },
  {
    name: 'Hannah Okonkwo',
    headline: 'Crypto · decentralized storage indexing',
    pedigree: 'Filecoin grant recipient',
    focusArea: 'Decentralized storage',
    alignment: 0.83,
    plvs: 68,
    plnProximity: 0.62,
    funds: ['CRYPTO'],
    sources: ['GitHub', 'Forum'],
    status: 'hold',
    feedback: 'needs-context',
    signals: ['nearNetwork'],
    lastSignalAt: '2026-06-08',
    topics: ['storage', 'indexing', 'web3'],
    github: 'hokonkwo',
  },
  {
    name: 'Daniel Roth',
    headline: 'Neuro · spiking-neural-net accelerator · tape-out Q3',
    pedigree: 'ETH Zürich · 2 hardware patents',
    focusArea: 'Neuromorphic hardware',
    alignment: 0.81,
    plvs: 64,
    plnProximity: 0.21,
    funds: ['NEURO'],
    sources: ['arXiv', 'Crunchbase'],
    status: 'in-review',
    lastSignalAt: '2026-06-05',
    topics: ['neuromorphic', 'hardware'],
  },
  {
    name: 'Sofia Marchetti',
    headline: 'PLVS · agentic data pipelines · 2 enterprise LOIs',
    pedigree: 'ex-Databricks staff eng',
    focusArea: 'AI agents',
    alignment: 0.79,
    plvs: 70,
    plnProximity: 0.48,
    funds: ['PLVS'],
    sources: ['LinkedIn'],
    status: 'new',
    signals: ['raising'],
    lastSignalAt: '2026-06-17',
    topics: ['data-pipelines', 'agents'],
    linkedin: 'https://linkedin.com/in/smarchetti',
  },
  {
    name: 'Ravi Deshmukh',
    headline: 'Crypto · on-chain identity primitives · authored EIP',
    pedigree: 'Ethereum core contributor',
    focusArea: 'ZK / cryptography',
    alignment: 0.77,
    plvs: 61,
    plnProximity: 0.7,
    funds: ['CRYPTO'],
    sources: ['GitHub', 'Mirror', 'Forum'],
    status: 'new',
    signals: ['nearNetwork', 'plAligned'],
    lastSignalAt: '2026-06-14',
    topics: ['identity', 'standards', 'ethereum'],
    github: 'ravid',
  },
  {
    name: 'Elena Vasquez',
    headline: 'PLVS · synthetic-biology tooling · early signal',
    pedigree: 'UCSF postdoc',
    focusArea: 'Synthetic biology',
    alignment: 0.71,
    plvs: 52,
    plnProximity: 0.18,
    funds: ['PLVS'],
    sources: ['Press'],
    status: 'new',
    lastSignalAt: '2026-05-30',
    topics: ['synbio', 'lab-automation'],
  },
  {
    name: 'Marcus Lee',
    headline: 'PLVS · edge-inference runtime · unclear stage',
    pedigree: 'ex-Qualcomm',
    focusArea: 'LLM infra',
    alignment: 0.66,
    plvs: 49,
    plnProximity: 0.29,
    funds: ['PLVS'],
    sources: ['GitHub'],
    status: 'hold',
    lastSignalAt: '2026-05-22',
    github: 'marcuslee',
  },
  {
    name: 'Noor Hassan',
    headline: 'Crypto · privacy-preserving ML · pre-product',
    pedigree: 'CMU PhD · strong publication record',
    focusArea: 'ZK / cryptography',
    alignment: 0.58,
    plvs: 44,
    plnProximity: 0.36,
    funds: ['CRYPTO', 'PLVS'],
    sources: ['arXiv'],
    status: 'new',
    signals: ['cofounder'],
    lastSignalAt: '2026-06-10',
    topics: ['privacy', 'ml', 'mpc'],
  },
  {
    name: 'Greta Olsen',
    headline: 'Neuro · wearable neurofeedback · consumer angle',
    pedigree: 'serial consumer-hardware founder',
    focusArea: 'Neurotech / BCI',
    alignment: 0.47,
    plvs: 31,
    plnProximity: 0.12,
    funds: ['NEURO'],
    sources: ['LinkedIn'],
    status: 'rejected',
    feedback: 'wrong-fund',
    lastSignalAt: '2026-04-28',
    linkedin: 'https://linkedin.com/in/golsen',
  },
  {
    name: 'Anika Sharma',
    headline: 'PLVS fit · distributed training scheduler · early traction',
    pedigree: 'ex-Google Brain · 3 NeurIPS papers',
    focusArea: 'LLM infra',
    alignment: 0.95,
    plvs: 89,
    plnProximity: 0.68,
    funds: ['PLVS'],
    sources: ['GitHub', 'arXiv', 'LinkedIn'],
    status: 'new',
    signals: ['raising', 'nearNetwork'],
    lastSignalAt: '2026-06-20',
    bio: 'Building an elastic scheduler for large-scale distributed training across heterogeneous clusters.',
    topics: ['training', 'scheduling', 'llm-infra'],
    github: 'anikasharma',
  },
  {
    name: 'Diego Fuentes',
    headline: 'Crypto fit · ZK rollup data availability · testnet live',
    pedigree: 'ex-StarkWare · core protocol',
    focusArea: 'ZK / cryptography',
    alignment: 0.91,
    plvs: 85,
    plnProximity: 0.6,
    funds: ['CRYPTO'],
    sources: ['GitHub', 'Mirror', 'Forum'],
    status: 'new',
    signals: ['cofounder', 'plAligned'],
    lastSignalAt: '2026-06-19',
    bio: 'Designing a data-availability layer for ZK rollups with sub-second proof times.',
    topics: ['zk', 'rollups', 'data-availability'],
    github: 'dfuentes',
  },
  {
    name: 'Mira Kovač',
    headline: 'PLVS · retrieval infra for agents · 1.1k stars',
    pedigree: 'ex-Elastic staff eng',
    focusArea: 'AI agents',
    alignment: 0.88,
    plvs: 82,
    plnProximity: 0.71,
    funds: ['PLVS'],
    sources: ['GitHub', 'LinkedIn'],
    status: 'new',
    signals: ['raising', 'stealth'],
    lastSignalAt: '2026-06-18',
    bio: 'Building low-latency retrieval and memory infrastructure for production agent systems.',
    topics: ['retrieval', 'agents', 'vector-db'],
    github: 'mirakovac',
  },
  {
    name: 'Jonas Weber',
    headline: 'Neuro fit · implantable neural decoder · animal trials',
    pedigree: 'EPFL · Neuralink alum',
    focusArea: 'Neurotech / BCI',
    alignment: 0.86,
    plvs: 74,
    plnProximity: 0.34,
    funds: ['NEURO', 'PLVS'],
    sources: ['arXiv', 'Press'],
    status: 'new',
    signals: ['raising'],
    lastSignalAt: '2026-06-16',
    bio: 'Developing a high-bandwidth implantable decoder for motor restoration.',
    topics: ['bci', 'neurotech', 'implants'],
  },
  {
    name: 'Leila Haddad',
    headline: 'PLVS · on-device LLM compression · pre-seed',
    pedigree: 'ex-Arm ML',
    focusArea: 'LLM infra',
    alignment: 0.78,
    plvs: 66,
    plnProximity: 0.42,
    funds: ['PLVS'],
    sources: ['GitHub'],
    status: 'new',
    signals: ['cofounder'],
    lastSignalAt: '2026-06-11',
    bio: 'Quantization and sparsity toolkit for running capable LLMs on edge devices.',
    topics: ['quantization', 'edge', 'llm-infra'],
    github: 'lhaddad',
  },
  {
    name: 'Oskar Lindqvist',
    headline: 'Crypto · decentralized GPU market · unclear traction',
    pedigree: 'serial infra founder',
    focusArea: 'Decentralized storage',
    alignment: 0.73,
    plvs: 60,
    plnProximity: 0.51,
    funds: ['CRYPTO'],
    sources: ['Mirror', 'Forum'],
    status: 'new',
    lastSignalAt: '2026-06-09',
    topics: ['depin', 'gpu', 'web3'],
  },
];

function hasSignal(seed: Seed, sig: Signal): boolean {
  return !!seed.signals?.includes(sig);
}

export const mockFounders: FounderDetail[] = SEEDS.map((seed, i) => ({
  founderId: `mock-founder-${i + 1}`,
  name: seed.name,
  criteriaHeadline: seed.headline,
  whyNow: seed.headline,
  pedigree: seed.pedigree,
  focusArea: seed.focusArea,
  alignmentMax: seed.alignment,
  plvsScore: seed.plvs,
  plvsRecommendation:
    seed.plvs != null && seed.plvs >= 80 ? 'Strong' : seed.plvs != null && seed.plvs >= 60 ? 'Consider' : undefined,
  plnProximity: seed.plnProximity,
  isRaising: hasSignal(seed, 'raising'),
  isCofounderSearch: hasSignal(seed, 'cofounder'),
  isComingOutOfStealth: hasSignal(seed, 'stealth'),
  nearNetwork: hasSignal(seed, 'nearNetwork'),
  plAligned: hasSignal(seed, 'plAligned'),
  sources: seed.sources,
  // Prototype: every founder starts unreviewed ('new').
  reviewState: { status: 'new' },
  lastSignalAt: `${seed.lastSignalAt}T12:00:00.000Z`,
  bio: seed.bio ?? null,
  topics: seed.topics ?? [],
  github: seed.github ?? null,
  website: seed.website ?? null,
  linkedin: seed.linkedin ?? null,
  twitter: seed.twitter ?? null,
  rawPayload: {
    fund_tags: seed.funds,
    focus_area: seed.focusArea,
    criteria_headline: seed.headline,
    pedigree: seed.pedigree,
    is_raising: hasSignal(seed, 'raising'),
    is_cofounder_search: hasSignal(seed, 'cofounder'),
    is_coming_out_of_stealth: hasSignal(seed, 'stealth'),
    near_network: hasSignal(seed, 'nearNetwork'),
    pl_aligned: hasSignal(seed, 'plAligned'),
    plvs_features: seed.funds.includes('PLVS')
      ? {
          domainMatch: Math.min(30, Math.round((seed.plvs ?? 0) * 0.33)),
          technicalDepth: Math.min(20, Math.round((seed.plvs ?? 0) * 0.22)),
          stageFit: Math.min(15, Math.round((seed.plvs ?? 0) * 0.16)),
          corroboration: Math.min(15, seed.sources.length * 5),
          recency: Math.min(10, 6 + (i % 4)),
          trajectory: Math.min(10, 4 + (i % 6)),
        }
      : undefined,
    provenance: seed.sources.map((src, j) => ({
      url: `https://example.com/${seed.github ?? 'profile'}/${j + 1}`,
      source: src,
      match_confidence: 0.6 + ((i + j) % 4) * 0.1,
      matched_anchors: seed.topics?.slice(0, 2) ?? [],
    })),
    // No warm_intro_paths: the Founder DB has no warm-intro engine (Investor DB feature).
    verification_status: undefined,
    verification_rationale: [],
    external_ids: (seed.github ? { github: seed.github } : {}) as Record<string, string>,
  },
}));

// ── KPI summary ───────────────────────────────────────────────────────────────

export const mockKpiSummary: KpiSummary = {
  newRecordsByFund: { PLVS: 7, NEURO: 3, CRYPTO: 4 },
  alignmentDistribution: { low: 3, medium: 4, high: 7 },
  sourceCoverage: { GitHub: 8, arXiv: 4, LinkedIn: 4, Crunchbase: 2, Press: 3, X: 1, Mirror: 2, Forum: 3 },
  weeklyNewRecords: [
    { weekStart: '2026-05-04', count: 5 },
    { weekStart: '2026-05-11', count: 8 },
    { weekStart: '2026-05-18', count: 6 },
    { weekStart: '2026-05-25', count: 11 },
    { weekStart: '2026-06-01', count: 9 },
    { weekStart: '2026-06-08', count: 14 },
  ],
};

export const mockSources = ['GitHub', 'arXiv', 'LinkedIn', 'Crunchbase', 'Press', 'X', 'Mirror', 'Forum'];

export const mockFocusAreas = [
  'AI agents',
  'LLM infra',
  'Verifiable compute',
  'ZK / cryptography',
  'Neurotech / BCI',
  'Neuromorphic hardware',
  'Robotics',
  'Decentralized storage',
  'Synthetic biology',
];

export const mockPage = {
  title: 'Founder DB',
  badge: 'Access Restricted to - PL Investment Team',
  subtitle: 'Database to determine qualified founders.',
};
