export enum ForumQueryKeys {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_TOPICS = 'GET_TOPICS',
  GET_TOPIC = 'GET_TOPIC',
  GET_VOTE_STATUS = 'GET_VOTE_STATUS',
  CHECK_GROUP_ACCESS = 'CHECK_GROUP_ACCESS',
}
