import type { StoredCv } from './types';

/**
 * The mock CV, and the two ways a `StoredCv` comes to exist in a prototype.
 *
 * **A genuine PDF, not a placeholder.** The resting card shows the file's first
 * page and the preview modal pages through it, so the mock has to be something
 * pdf.js can open. `buildSamplePdf` writes a minimal one-page PDF — two standard
 * fonts, a content stream, a correct xref — as bytes on the client and hands back
 * a blob URL. Hand-written rather than generated by a library so the prototype
 * pulls in nothing; the shape follows the PDF 1.4 spec's smallest valid file.
 *
 * Client-only: `URL.createObjectURL` needs a `window`, and prototype routes
 * server-render (see `project-prototypes-ssr-browser-libs`). The URL is built
 * lazily on first use and cached, so every card and modal shares one.
 */

const SAMPLE_FILE_NAME = 'polina-bublii-cv.pdf';

/* The page the mock renders. Plain ASCII on purpose — a Type1 standard font
   with no encoding declared renders WinAnsi, and the builder does not escape
   anything beyond parentheses and backslashes. */
const SAMPLE_LINES: Array<{ text: string; font: 'bold' | 'regular'; size: number; gapBefore?: number }> = [
  { text: 'Polina Bublii', font: 'bold', size: 22 },
  { text: 'Senior Protocol Engineer - Berlin, Germany', font: 'regular', size: 11, gapBefore: 6 },
  { text: 'polina@lattice.dev - linkedin.com/in/polina-bublii', font: 'regular', size: 10, gapBefore: 4 },
  { text: 'Experience', font: 'bold', size: 13, gapBefore: 26 },
  { text: 'Senior Protocol Engineer, Lattice Compute', font: 'bold', size: 11, gapBefore: 12 },
  { text: 'March 2021 - Present, Remote', font: 'regular', size: 10, gapBefore: 4 },
  { text: 'Cut p95 handshake latency by 40% across the transport layer.', font: 'regular', size: 10, gapBefore: 4 },
  { text: 'Owned the QUIC upgrade path and the connection manager rewrite.', font: 'regular', size: 10, gapBefore: 3 },
  { text: 'Maintainer, transports, libp2p', font: 'bold', size: 11, gapBefore: 14 },
  { text: 'June 2022 - Present', font: 'regular', size: 10, gapBefore: 4 },
  { text: 'QUIC transport and connection upgrade paths.', font: 'regular', size: 10, gapBefore: 4 },
  { text: 'Skills', font: 'bold', size: 13, gapBefore: 26 },
  { text: 'Distributed Systems - Rust - libp2p - Consensus - Networking', font: 'regular', size: 10, gapBefore: 10 },
];

const escapePdfText = (text: string) => text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

/** A one-page A4 PDF as bytes. See the note at the top of the file. */
export function buildSamplePdf(): Uint8Array {
  const margin = 56;
  let y = 842 - 72;
  const ops: string[] = [];
  for (const line of SAMPLE_LINES) {
    y -= (line.gapBefore ?? 0) + line.size;
    const font = line.font === 'bold' ? '/F1' : '/F2';
    ops.push(`BT ${font} ${line.size} Tf ${margin} ${y} Td (${escapePdfText(line.text)}) Tj ET`);
  }
  const content = ops.join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let out = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefAt = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) out += `${String(offset).padStart(10, '0')} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;

  /* Every character above is ASCII, so char code === byte. */
  const bytes = new Uint8Array(out.length);
  for (let i = 0; i < out.length; i += 1) bytes[i] = out.charCodeAt(i) & 0xff;
  return bytes;
}

let sampleUrl: string | null = null;

/** The mock's bytes as a blob URL — built once per page, on the client only. */
export function sampleCvUrl(): string | undefined {
  if (typeof window === 'undefined') return undefined;
  if (!sampleUrl) {
    const bytes = buildSamplePdf();
    sampleUrl = URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' }));
  }
  return sampleUrl;
}

/**
 * The returning member's CV — uploaded some weeks back, like the rest of
 * `FILLED_PROFILE`, so the resting card shows a date that is not today.
 *
 * `size` is a stated number rather than the generated file's real one: a
 * hand-built one-page PDF weighs ~2KB, and "2KB" under a CV reads as a bug.
 * The preview still opens the real bytes; only the label is the size a CV
 * actually has. `url` is filled in by `withSampleUrl` at render, because the
 * blob can only be made on the client.
 */
export const MOCK_STORED_CV: StoredCv = {
  fileName: SAMPLE_FILE_NAME,
  size: 248 * 1024,
  uploadedAt: '2026-08-12T10:24:00.000Z',
};

/** The mock with its client-built URL attached — a no-op for a CV that has one. */
export function withSampleUrl(cv: StoredCv): StoredCv {
  if (cv.url) return cv;
  return { ...cv, url: sampleCvUrl() };
}

/**
 * The record a dropped file becomes, the moment it has been read.
 *
 * "The upload is the store": production uploads the document before parsing it
 * (`parseCv` posts the file, then polls), so by the time the review is on screen
 * the file already exists on the server. This mirrors that — the card shows the
 * new file whether or not the review's Save is pressed, and Cancel on the review
 * cancels the fill-in, not the upload.
 *
 * A real file previews itself: the blob URL is the file the person just dropped,
 * so the thumbnail is honest even in a prototype. (`sampleSize` is unused here on
 * purpose — the dropped file's own size is the truth.)
 */
export function storedCvFromFile(file: File): StoredCv {
  return {
    fileName: file.name,
    size: file.size,
    uploadedAt: new Date().toISOString(),
    url: typeof window === 'undefined' ? undefined : URL.createObjectURL(file),
  };
}

/** "12 Aug 2026" — the board's own short date form (`JobDetailPane` dates). */
export function formatUploadedDate(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

/** "PDF" from "polina-bublii-cv.pdf" — the meta line's first fact. */
export function fileKind(fileName: string): string {
  const ext = fileName.split('.').pop();
  return ext && ext !== fileName ? ext.toUpperCase() : 'File';
}

/** Whether the preview can render it — pdf.js opens PDFs and nothing else. */
export const isPdfName = (fileName: string) => fileKind(fileName) === 'PDF';
