name: Secret Detection

on:
  push:
    branches:
      - '**' # Run on all branches

jobs:
  secret-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Secret Detection Script
        run: node helper/secret-check.js
