name: Secretlint on Changed Files

on: [push, pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install secretlint
        run: npm install --save-dev secretlint

      - name: Run secretlint
        run: npx secretlint "**/*"